services:
  pokemon-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: pokemon_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"  
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: